use_frameworks!

platform :ios, '10.0'

target 'WZFullscreenPopGesture_Example' do
  pod 'WZFullscreenPopGesture', :path => '../'

  target 'WZFullscreenPopGesture_Tests' do
    inherit! :search_paths

    
  end
  
  post_install do |installer|
        installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
       end
  end
end

